server:
  port: 8761
  
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://admin:123456@localhost:${server.port}/eureka/
spring:

  application:    name: spring-cloud-service
      security:    user:      name: admin
      password: 123456